"""Data ingestion contracts and manifest utilities."""

from src.ingestion.contracts import (
    PROHIBITED_RECOMMENDATION_FIELDS,
    REQUIRED_CONTRACT_FIELDS,
    REQUIRED_DATASETS,
    get_contract,
    list_contract_datasets,
    load_ingestion_contracts,
    validate_dataset_columns,
    validate_ingestion_contracts,
    validate_manual_file,
)
from src.ingestion.coverage_report import (
    COVERAGE_REPORT_COLUMNS,
    DEFAULT_COVERAGE_REQUIRED_FIELDS,
    build_data_coverage_report,
    has_prohibited_recommendation_columns as has_prohibited_coverage_columns,
    save_data_coverage_report,
)
from src.ingestion.disclosure_warning_ingestion import (
    DISCLOSURE_STATUS_RAW_FILENAME,
    REAL_SOURCE_UNAVAILABLE as DISCLOSURE_REAL_SOURCE_UNAVAILABLE,
    build_disclosure_warning_coverage,
    build_manual_review_candidates,
    ingest_disclosure_warning_data,
    save_disclosure_warning_raw,
    save_manual_review_candidates as save_disclosure_manual_review_candidates,
    standardize_disclosure_warning_raw,
)
from src.ingestion.financial_statement_ingestion import (
    FINANCIAL_STATEMENT_RAW_FILENAME,
    REAL_SOURCE_UNAVAILABLE as FINANCIAL_REAL_SOURCE_UNAVAILABLE,
    build_financial_missing_data_report,
    build_financial_statement_coverage,
    ingest_financial_statement_data,
    save_financial_statement_raw,
    save_missing_data_report as save_financial_missing_data_report,
    standardize_financial_statement_raw,
)
from src.ingestion.manifest import (
    MANIFEST_FIELDS,
    create_ingestion_manifest_record,
    create_manifest_from_validation,
    load_ingestion_manifest,
    save_ingestion_manifest,
    validate_manifest_record,
)
from src.ingestion.pipeline_dry_run import (
    DRY_RUN_STAGES,
    DRY_RUN_SUMMARY_FIELDS,
    ERROR_COLUMNS as PIPELINE_DRY_RUN_ERROR_COLUMNS,
    MANUAL_REVIEW_COLUMNS as PIPELINE_MANUAL_REVIEW_COLUMNS,
    PIPELINE_DATASETS,
    has_prohibited_recommendation_columns as has_prohibited_pipeline_columns,
    run_pipeline_dry_run,
    save_pipeline_dry_run_reports,
)
from src.ingestion.market_price_ingestion import (
    MARKET_PRICE_RAW_FILENAME,
    REAL_SOURCE_UNAVAILABLE as MARKET_PRICE_REAL_SOURCE_UNAVAILABLE,
    build_market_price_coverage,
    build_market_price_ticker_log,
    ingest_market_price_data,
    save_market_price_raw,
    save_ticker_log,
    standardize_market_price_raw,
)
from src.ingestion.universe_profile_ingestion import (
    COMPANY_PROFILE_RAW_FILENAME,
    REAL_SOURCE_UNAVAILABLE,
    UNIVERSE_RAW_FILENAME,
    build_universe_profile_coverage,
    has_prohibited_recommendation_columns,
    ingest_universe_and_company_profiles,
    save_coverage_summary,
    save_universe_profile_raw_outputs,
    standardize_company_profile_raw,
    standardize_universe_raw,
)

__all__ = [
    "MANIFEST_FIELDS",
    "PROHIBITED_RECOMMENDATION_FIELDS",
    "REAL_SOURCE_UNAVAILABLE",
    "REQUIRED_CONTRACT_FIELDS",
    "REQUIRED_DATASETS",
    "COVERAGE_REPORT_COLUMNS",
    "COMPANY_PROFILE_RAW_FILENAME",
    "DEFAULT_COVERAGE_REQUIRED_FIELDS",
    "DISCLOSURE_REAL_SOURCE_UNAVAILABLE",
    "DISCLOSURE_STATUS_RAW_FILENAME",
    "DRY_RUN_STAGES",
    "DRY_RUN_SUMMARY_FIELDS",
    "FINANCIAL_REAL_SOURCE_UNAVAILABLE",
    "FINANCIAL_STATEMENT_RAW_FILENAME",
    "MARKET_PRICE_RAW_FILENAME",
    "MARKET_PRICE_REAL_SOURCE_UNAVAILABLE",
    "PIPELINE_DATASETS",
    "PIPELINE_DRY_RUN_ERROR_COLUMNS",
    "PIPELINE_MANUAL_REVIEW_COLUMNS",
    "UNIVERSE_RAW_FILENAME",
    "build_data_coverage_report",
    "build_disclosure_warning_coverage",
    "build_financial_missing_data_report",
    "build_financial_statement_coverage",
    "build_manual_review_candidates",
    "build_market_price_coverage",
    "build_market_price_ticker_log",
    "build_universe_profile_coverage",
    "create_ingestion_manifest_record",
    "create_manifest_from_validation",
    "get_contract",
    "has_prohibited_coverage_columns",
    "has_prohibited_pipeline_columns",
    "has_prohibited_recommendation_columns",
    "ingest_disclosure_warning_data",
    "ingest_financial_statement_data",
    "ingest_market_price_data",
    "ingest_universe_and_company_profiles",
    "list_contract_datasets",
    "load_ingestion_contracts",
    "load_ingestion_manifest",
    "run_pipeline_dry_run",
    "save_coverage_summary",
    "save_data_coverage_report",
    "save_disclosure_manual_review_candidates",
    "save_disclosure_warning_raw",
    "save_financial_missing_data_report",
    "save_financial_statement_raw",
    "save_ingestion_manifest",
    "save_market_price_raw",
    "save_pipeline_dry_run_reports",
    "save_ticker_log",
    "save_universe_profile_raw_outputs",
    "standardize_company_profile_raw",
    "standardize_disclosure_warning_raw",
    "standardize_financial_statement_raw",
    "standardize_market_price_raw",
    "standardize_universe_raw",
    "validate_dataset_columns",
    "validate_ingestion_contracts",
    "validate_manifest_record",
    "validate_manual_file",
]
